### ISSUE TITLE
Link para ver todas as edições da Weekly

### ISSUE THREAD

**Issue by jaydson** [braziljs/braziljs.org#102]
Adicionar link abaixo das 3 últimas Weeklys para a listagem completa de Weeklys.

**Comment by keppelen** [comment]
Eu deixaria como estar, e colocaria o link direto para listagem no site do ZOFE.

**Comment by zenorocha** [comment]
Ainda existe a necessidade de se criar uma página para listar todas as edições da Weekly. Podcasts é outra história, mas também precisa agora que listamos não só o ZOFE mas o CodeTalks também.

**Comment by jaydson** [comment]
Fechando essa issue aqui visando uma reformulação breve.
