### ISSUE TITLE
Seção de Vídeos

### ISSUE THREAD

**Issue by jaydson** [braziljs/braziljs.org#104]
Podemos criar uma seção de vídeos em algum lugar do site.  
Temos muitos vídeos no canal do Youtube, e a ideia é que em 2014 esse número aumente.
Que acham?

**Comment by keppelen** [comment]
Ainda temos essa necessidade?

**Comment by felquis** [comment]
O Zeno lançou essa ideia no ideias, não sei o que irá virar.

2015-02-05 21:26 GMT-02:00 Giovanni keppelen <notifications@github.com>:

> Ainda temos essa necessidade?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braziljs/braziljs.org/issues/104#issuecomment-73152263>
> .
>



-- 
Felquis Gimenes - Front-end
felquis.com +55 011 95980 2233

**Comment by zenorocha** [comment]
Acho que independente do que possa a vir na issue de Vídeos no ideias, podemos linkar as playlists nossas do Youtube por aqui. Palestras dos anos anteriores, não só da BrazilJS mas de outros eventos brasileiros.

**Comment by keppelen** [comment]
Não é mais simples e viável, colocar um link no header, algo videos, e mandar para listagem do youtube?

**Comment by zenorocha** [comment]
É sim Gio, vamos com essa, até porque o canal já está bem organizado.
