### ISSUE TITLE
Registrar histórico de eventos no Lanyrd

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#119]
A medida que o tempo vai passando e novas edições de cada evento vão acontecendo, percebemos que muitas informações são perdidas na web por falta de trabalho pós-evento, por exemplo:

* Quem palestrou no evento X
* Quem participou no evento X
* Onde foi o evento X
* Fotos do evento X
* E principalmente, slides e vídeos de cada palestra no evento X

Existe uma ferramenta chamada [Lanyrd](http://lanyrd.com/) que pode ser útil para "eternizar" informações de todos os eventos que nós ajudamos no Brasil, ao invés de serem jogadas fora quando o novo site da próxima edição do site do evento vier à tona.

---

**Missão:** Cadastrar todos os eventos que listamos aqui, oferecendo a maior quantidade possível de informações. Lembrar de colocar coisas como local do evento, toda a agenda e os slides/vídeos de cada uma das talks.

Exemplos:
* http://lanyrd.com/2013/braziljs/
* http://lanyrd.com/2013/braziljs/scwrkd/

A partir do momento que tivermos tudo lá, linkamos os eventos em [braziljs.org/eventos](http://braziljs.org/eventos/) direto para suas páginas no Lanyrd.

OBS: Qualquer usuário pode editar qualquer evento, por isso não precisa criar novos eventos caso ele já exista lá. Tomem cuidado para não duplicar eventos.

**Comment by jaydson** [comment]
Issue velha.
