### ISSUE TITLE
Criar formulário de contato

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#157]
O endereço de email contact@braziljs.org está desativado e sem previsão para voltar.

Pensamos então em colocar um [formulário do wufoo](http://www.wufoo.com/) na [página de contato](http://braziljs.org/contato/).

O que acham? Quem pode ajudar mandando um pull request com isso?

**Comment by diogomoretti** [comment]
eu posso adicionar sim! hoje quando chegar em casa eu coloco.

**Comment by randsonjs** [comment]
Eu estava fazendo, mas o formulário no wufoo pede um email para recebimento. Qual e-mail será usado para isso?

**Comment by zenorocha** [comment]
Pode ser mais de um email @randsonjs?

**Comment by randsonjs** [comment]
Apenas um :(

Tem como também redirecionar para aplicações como Twitter, Mailchimp... Mais ai precisaria de acesso a conta para tal modificação.

**Comment by zenorocha** [comment]
Desculpa a demora, ambos os emails oficiais tão off e esquecemos que o formulário tem que estar atrelado a conta da BrazilJS no Wufoo para futuras edições :/

Vamos colocar um email provisório enquanto isso.

**Comment by zenorocha** [comment]
Valeu @randsonjs!

**Comment by zenorocha** [comment]
http://braziljs.org/contato/
