### ISSUE TITLE
Espaço para traduções

### ISSUE THREAD

**Issue by ericdouglas** [braziljs/braziljs.org#158]
Pessoal, como iremos incluir as traduções no site da braziljs?

Pensei em: 

1. Adicionarmos um item no header, ficando: Eventos | Projetos | **Traduções**
2. A página `/traducoes` teria a listagem das tecnologias, no mesmo formato da página `/eventos`, ai incluiríamos uma imagem para cada tecnologia (JavaScript, NodeJS, Angular, MongoDB, React...)
3. Listamos na página `traducoes/:topico` todas as traduções dessa tech, e os arquivos ficarão [aqui](https://github.com/braziljs/braziljs.org/tree/master/src/documents/blog), onde criamos uma pasta para cada assunto.

ps: No caso estou pensando em agruparmos artigos, livros podemos deixar como um tópico em `/traducoes`, e em `/traducoes/books`, listamos todos os livros traduzidos *linkando* para seu source.

O que acham?

cc/ @zenorocha @joaostein @randsonjs @diogomoretti

**Comment by randsonjs** [comment]
### /traducoes

A página `/traducoes` listaria as tags/categorias com imagem para cada uma delas?

Eu penso que poderia ser uma listagem de posts(traduções no caso) comum. Alguns tendo imagens de capa outros não. Ou apenas links para um conteúdo externo.

Listar categorias onde deveria listar os posts para mim é extranho e dificilmente eu vejo isso na web. A página de `/eventos` é diferente porque tem poucos eventos e eles não tem um "conteúdo interno".

### traducoes/:topico

Acho que poderiamos mudar o layout de post. Colocando uma coluna para informações sobre o tradutor/revisor e um espaço para as tags bem como o usuário que postou e a data da postagem. Assunto que relatei na issue #161.

Como uma tradução na maioria das veses é feita por várias pessoas, criariamos um usuário chamado `community` com a fotinha da BrazilJS ;)

**Comment by jaydson** [comment]
Acho a ideia muito boa, porém já se passou muito tempo.
Com a nova reformulação que estamos planejando, podemos pensar em algo nesse sentido também.
