### ISSUE TITLE
Informações do post

### ISSUE THREAD

**Issue by randsonjs** [braziljs/braziljs.org#161]
Senti falta de algumas informações do post como Usuário que postou, Data do post...

Tem na página inicial, porém não informa o ano. Fiquei um pouco perdido quanto a isso.

**Comment by zenorocha** [comment]
É verdade, eu também sinto @randsonjs, hoje em dia é só um texto corrido e pronto.

Você pode mandar um pull request com essas funcionalidades?

**Comment by jaydson** [comment]
Estamos planejando uma migração, então essa issue não faz mais sentido.
