### ISSUE TITLE
Adicionar DevCast Day

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#164]
http://www.eventick.com.br/devcastday

Eu sei que já passou mas seria legal colocar ali a título histórico ;)

/cc @felquis

**Comment by felquis** [comment]
Bacana, obrigado por notar, quando sentar a frente de um computador
enviarei um pull request.
Em 25/01/2015 13:15, "Zeno Rocha" <notifications@github.com> escreveu:
