### ISSUE TITLE
Adicionar Front-End Experience

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#169]
Mesmo sem data e preço definidos já podemos criar buzz em cima dele.

https://www.facebook.com/frontendexperience

/cc @luiztiago @davidsonfellipe

**Comment by luiztiago** [comment]
@zenorocha Show!! Muito em breve teremos mais detalhes!

**Comment by keppelen** [comment]
@zenorocha  Assim que fecharmos mais detalhes, vamos add na pagina de eventos, aqui e lanyrd.

**Comment by zenorocha** [comment]
Por que nao add agora?

**Comment by davidsonfellipe** [comment]
daqui a pouco

**Comment by luiztiago** [comment]
https://github.com/braziljs/braziljs.org/pull/172

**Comment by felquis** [comment]
Valeu Luiz :kiss:
