### ISSUE TITLE
Adicionar Eloquent Javascript na página de projetos

### ISSUE THREAD

**Issue by randsonjs** [braziljs/braziljs.org#175]

**Comment by zenorocha** [comment]
Precisamos de uma logo e informação de "como posso ajudar?"

**Comment by randsonjs** [comment]
Vou dar um jeito nisso e envio como Pull Request ;)

**Comment by SauloSilva** [comment]
@zenorocha e @randsonjs  integração feita http://braziljs.org/projetos/

**Comment by zenorocha** [comment]
Irado!
