### ISSUE TITLE
Corrigir eventos duplicados

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#186]
![screen shot 2015-02-13 at 11 51 55 am](https://cloud.githubusercontent.com/assets/398893/6189110/c246790e-b376-11e4-9bad-713fa0048b2d.png)

/cc @mateusortiz

**Comment by mateusortiz** [comment]
não estou entendo porque ele está duplicando os eventos, se está tudo normal.

**Comment by randsonjs** [comment]
Rapaz, aqui está normal.

![capturar](https://cloud.githubusercontent.com/assets/4191734/6193444/a235a8b8-b391-11e4-8344-6d786bfb5c33.PNG)

**Comment by diogomoretti** [comment]
Arrumei isso em 9ad85640d5a1a1abd7703de0ab56c53a94d424ea

**Comment by zenorocha** [comment]
Coisa linda @diogomoretti!

**Comment by mateusortiz** [comment]
:heart: @diogomoretti
