### ISSUE TITLE
Adicionar botão do GitHub ao lado do Facebook e Twitter

### ISSUE THREAD

**Issue by randsonjs** [braziljs/braziljs.org#190]

**Comment by lucascarvalho** [comment]
@randsonjs tem os oficiais: 
https://github.com/blog/273-github-ribbons

E os não oficiais: 
https://buttons.github.io/ 
https://ghbtns.com/

Só escolher.

**Comment by randsonjs** [comment]
O não oficial Star do repositório é o mais top! ;)
