### ISSUE TITLE
Adicionar NiteroiJS

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#193]
http://www.eventick.com.br/niteroijs

**Comment by mateusortiz** [comment]
@zenorocha qual image adiciono para a capa do evento?

**Comment by mateusortiz** [comment]
fiz uma image para o NiteroiJS, enquanto não tem logo, posso colocar essa?
![niteroijs](http://cl.ly/image/0N0Y242M2f27/niteroijs.png)

**Comment by zenorocha** [comment]
Criar uma marca sem consultar o organizador não é uma boa ideia, sugiro falar com o @leobalter antes

**Comment by diogomoretti** [comment]
concordo com o @zenorocha. @mateusortiz, poderiamos criar uma "imagem não disponivel" ou algo do tipo. você poderia criar uma? (ai a gente pode usar para outros eventos)

**Comment by zenorocha** [comment]
Boa!

**Comment by leobalter** [comment]
A arte deve sair nesse fds, mas está OK pra usarem um placeholder.

**Comment by mateusortiz** [comment]
Ok, desculpa criar sem falar, e vou criar uma "Imagem não disponivel"!

**Comment by mateusortiz** [comment]
Criei uma image para usarmos em outros eventos, vejam o que acham?
![Image](http://cl.ly/image/1I0p3F3X0A2p/not-found.png)

**Comment by zenorocha** [comment]
:+1:
