### ISSUE TITLE
BrazilJS Weekly & www.braziljs.org

### ISSUE THREAD

**Issue by learningjs** [braziljs/braziljs.org#205]
1 Confirmar assinatura (mail)
2 clicar em "continuar para o nosso site" (na pagina de confirma)
3 vai para [www.braziljs.org](http://www.braziljs.org/)
4 "This webpage is not available"
5 fix: [braziljs.org/](http://braziljs.org/)

**Comment by learningjs** [comment]
Ops, tem repo da newsletter :)

**Comment by randsonjs** [comment]
Mas é válido para o www.braziljs.org também :)
