### ISSUE TITLE
Menu para comunidades

### ISSUE THREAD

**Issue by pedropolisenso** [braziljs/braziljs.org#214]
Como o site tem menus para Eventos, projetos e agora blog e vídeos, achei que poderia ser legal um menu para listar os "grupos das cidades locais". Percebi que na organização BrazilJS tem repositórios da galera de maceió, Rio, Sampa, BH, POA e etc. O objetivo seria listar apenas as comunidades locais de cada estado lincando para o site ou para seu repositório no github.

Acho que iria ajudar a galera que não conhece ou não sabe como buscar e conhecer comunidades locais e ajudaria a galera do interior de cada cidade.

**Comment by zenorocha** [comment]
+1

**Comment by diogomoretti** [comment]
Falei com @jaydson ontem. Ele está providenciando algo nesse sentido =]

**Comment by pedropolisenso** [comment]
Show! :+1:

**Comment by jaydson** [comment]
Vou fechar essa issue, em breve teremos uma solução melhor.
