### ISSUE TITLE
Site caiu

### ISSUE THREAD

**Issue by SauloSilva** [braziljs/braziljs.org#216]
Olá entrei hoje no site e verifiquei que esta fora.

/cc @diogomoretti

**Comment by diogomoretti** [comment]
Pode ser alguma coisa com o domínio. Você poderia verificar @jaydson?

**Comment by jaydson** [comment]
Sim, algo com o domínio. Valeu pessoal, vou resolver aqui.

**Comment by jaydson** [comment]
And we're back: http://braziljs.org/

Era um problema de DNS mesmo.

**Comment by SauloSilva** [comment]
:+1:

**Comment by diogomoretti** [comment]
:+1:
