### ISSUE TITLE
Conteúdo dinâmico quebrado em produção?

### ISSUE THREAD

**Issue by mkautzmann** [braziljs/braziljs.org#218]
Acessei o http://braziljs.org hoje e percebi que os conteúdos de podcast e weekly não carregaram.

Abaixo screenshot do problema:

![braziljs_org](https://cloud.githubusercontent.com/assets/1051644/10799980/d2f89166-7d96-11e5-900a-43f7d5cd77b7.jpg)

Alguém confirma esta situação?

**Comment by zenorocha** [comment]
Confirmado. Usavamos o Yahoo Pipes para converter os XMLs para JSON e consumir no site, mas o serviço foi descontinuado. Precisamos de algo para substituir isso :/

**Comment by mkautzmann** [comment]
Vejo duas opções:

1) Talvez subir um script Node.JS para fazer essa conversão rodando no Heroku. Assim teríamos controle sobre o serviço.

2) Esquecer a conversão XML -> JSON e usar XML direto. Talvez com essa [API do jQuery](https://api.jquery.com/jQuery.parseXML/).

**Comment by diogomoretti** [comment]
Andei buscando alternativas, mas todas procuram fazer um crawler (pegar dados de uma página) ou fazer merge de serviços (asana, dropbox...)

**Comment by jaydson** [comment]
Vamos ter que achar uma melhor maneira de fazer isso mesmo.
Estou pensando em uma reformulação, e já vou tratar disso.

**Comment by diogomoretti** [comment]
Também prefiro uma reformulação, inclusive usando CI (travis), onde a cada modificação no master ele já dê um build.

**Comment by diogomoretti** [comment]
Vou fechar essa issue já que teremos que fazer uma reformulação.
