### ISSUE TITLE
Front In POA

### ISSUE THREAD

**Issue by mkautzmann** [braziljs/braziljs.org#223]
Olá pessoal.

Notei que o Front in POA não aparece no site http://braziljs.org como evento próximo.

Posso até adicionar. @felipenmoura e @jaydson o que vocês acham?

**Comment by mateusortiz** [comment]
pode adicionar sim, seria ótimo @mkautzmann :+1:

**Comment by mkautzmann** [comment]
Resolvido no merge da #224.
