### ISSUE TITLE
Redirecionar URLs quebradas

### ISSUE THREAD

**Issue by zenorocha** [braziljs/braziljs.org#94]

**Comment by keppelen** [comment]
Ainda vamos fazer esse? Ou podemos matar a issue?

**Comment by zenorocha** [comment]
Tenho que dar um confere no Google Webmasters, aí fechamos.

**Comment by keppelen** [comment]
Quem tem a conta?

**Comment by jaydson** [comment]
Fechando já que com uma reformulação não fará mais sentido.
